---
name: 'deploy'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master

env:
  NODE_ENV: ${{ secrets.NODE_ENV }}
  PORT: ${{ secrets.PORT }}
  APP_NAME: ${{ secrets.APP_NAME }}
  PARSE_DASHBOARD_MOUNT: ${{ secrets.PARSE_DASHBOARD_MOUNT }}
  PARSE_API_MOUNT: ${{ secrets.PARSE_API_MOUNT }}
  PARSE_API_APP_ID: ${{ secrets.PARSE_API_APP_ID }}
  PARSE_API_MASTER_KEY: ${{ secrets.PARSE_API_MASTER_KEY }}
  PARSE_API_SERVER_URL: ${{ secrets.PARSE_API_SERVER_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: create env file
      run: |
        touch .env
        echo NODE_ENV=$NODE_ENV >> .env
        echo PORT=$PORT >> .env
        echo APP_NAME=$APP_NAME >> .env
        echo PARSE_DASHBOARD_MOUNT=$PARSE_DASHBOARD_MOUNT >> .env
        echo PARSE_API_MOUNT=$PARSE_API_MOUNT >> .env
        echo PARSE_API_APP_ID=$PARSE_API_APP_ID >> .env
        echo PARSE_API_MASTER_KEY=$PARSE_API_MASTER_KEY >> .env
        echo PARSE_API_SERVER_URL=$PARSE_API_SERVER_URL >> .env
      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@caledonia.quanlabs.com/caledonia'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}